# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d62331a9a321dad619625306d368544d93ffc45839e57054f0d0f0bd20e08f656abecf719a372255bb1a95bb42a82eda183cc1dd35bc15b6977f20e03aaa5bac

test:
  secret_key_base: 6820c2fadb755872ff5260c6085641330977e530450ddecbb8875da9ee59ebace632f7d79d95d9db59ddc3ee6add11beed9e57c139e425cd08ff7148091dcc75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
